In [25]:
import pandas as pd 
import numpy as np

In [26]:
my_list=[1,2,3,4]
labels= ['a','b','c','d']
pd.Series(my_list,index=labels)

a    1
b    2
c    3
d    4
dtype: int64

In [27]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
c = ['Name','age','city','salary']
df2 = pd.DataFrame(data_list,columns=c)
df2

    Name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df2[['Name','age']]

    Name  age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [30]:
df2["Experiance"]=[1,2,3,4]

In [31]:
df2.drop('Experiance',axis=1,inplace=True)

In [23]:
df2

    Name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [36]:
print(df2.loc[[0,1]])

   Name  age      city  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [40]:
df2.loc[[2,3]][['Name','age']]

    Name  age
2  Peter   29
3  Linda   42

In [44]:
df2[(df2['age']>30) & (df2['city']=='Paris')]

   Name  age   city  salary
1  Anna   34  Paris   70000

# **Missing Data**

In [45]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [47]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [50]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [54]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [56]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [59]:
values ={'A':100,'B':200,'C':400,'D':400} 
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# **Merging and joint**

In [60]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [61]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [62]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [64]:
pd.merge(employees,salaries,on='employee_id',how="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [65]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [66]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [69]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [70]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [72]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [73]:
df2

   score
2     85
3     90
4     75

In [75]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [78]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
print(df)

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [84]:
df.groupby('Store')['Sales'].mean()

Store
S1    180.0
S2    195.0
Name: Sales, dtype: float64

In [89]:
df['Sales'].agg(['mean','median','max','sum','count'])

mean       187.5
median     190.0
max        300.0
sum       1500.0
count        8.0
Name: Sales, dtype: float64

In [90]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    240     32   John  January      Q1
1  2023-01-02       B   West    197     16   Mary  January      Q1
2  2023-01-03       C  North    509     34    Bob  January      Q1
3  2023-01-04       D  South    155     41  Alice  January      Q1
4  2023-01-05       A   East    796     70   John  January      Q1
5  2023-01-06       B   West    342     60   Mary  January      Q1
6  2023-01-07       C  North    726     26    Bob  January      Q1
7  2023-01-08       D  South    523     77  Alice  January      Q1
8  2023-01-09       A   East    559     69   John  January      Q1
9  2023-01-10       B   West    437     81   Mary  January      Q1
10 2023-01-11       C  North    365     68    Bob  January      Q1
11 2023-01-12       D  South    171     99  Alice  January      Q1
12 2023-01-13       A   East    218     93   John  January      Q1
13 2023-01-14       B   West    237     32   Mary  January      Q1
14 2023-01-15       C  North    889     17    Bob  January      Q1
15 2023-01-16       D  South    353     90  Alice  January      Q1
16 2023-01-17       A   East    334     64   John  January      Q1
17 2023-01-18       B   West    491     67   Mary  January      Q1
18 2023-01-19       C  North    275     66    Bob  January      Q1
19 2023-01-20       D  South    290     65  Alice  January      Q1

In [93]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='max')

Product      A      B      C      D
Region
East     796.0    NaN    NaN    NaN
North      NaN    NaN  889.0    NaN
South      NaN    NaN    NaN  523.0
West       NaN  491.0    NaN    NaN

In [96]:
pd.crosstab(df['Product'],df['Region'])

Region   East  North  South  West
Product
A           5      0      0     0
B           0      0      0     5
C           0      5      0     0
D           0      0      5     0