In [25]:
import pandas as pd 
import numpy as np

In [26]:
my_list=[1,2,3,4]
labels= ['a','b','c','d']
pd.Series(my_list,index=labels)

a    1
b    2
c    3
d    4
dtype: int64

In [27]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
c = ['Name','age','city','salary']
df2 = pd.DataFrame(data_list,columns=c)
df2

    Name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [29]:
df2[['Name','age']]

    Name  age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [30]:
df2["Experiance"]=[1,2,3,4]

In [31]:
df2.drop('Experiance',axis=1,inplace=True)

In [23]:
df2

    Name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.loc()